Added mcp building functions to builder script
Signed-off-by: Michael Engel <mengel@redhat.com>

diff --git a/tools/claude-box-builder b/tools/claude-box-builder
--- a/tools/claude-box-builder
+++ b/tools/claude-box-builder
@@ -3,6 +3,7 @@
 SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
 ROOT_DIR="${SCRIPT_DIR}"/..
 SUBMODULES_DIR="${ROOT_DIR}"/submodules
+MCP_SUBMODULES_DIR="${ROOT_DIR}"/submodules/mcp
 
 SKILLS_DIR="${ROOT_DIR}"/skills
 ANTHROPIC_SKILLS_REPO="anthropic"
@@ -14,6 +15,8 @@ AGENT_DIR="${ROOT_DIR}"/agents
 AGENCY_AGENT_REPO="agency"
 AGENCY_AGENT_DIR="${AGENT_DIR}"/"${AGENCY_AGENT_REPO}"
 
+MCP_DIR="${ROOT_DIR}"/mcp-server
+
 TMP_OUT_ROOT_DIR="${ROOT_DIR}"/out
 
 OCI_REGISTRY="quay.io"
@@ -22,11 +25,16 @@ PROJECT_NAME="claude-box"
 
 SKILL_ARTIFACT_PREFIX="skill"
 AGENT_ARTIFACT_PREFIX="agent"
+MCP_IMAGE_PREFIX="mcp"
 
 clean() {
     echo "Removing temporary artifacts..."
     rm -rf "${TMP_OUT_ROOT_DIR}"
 }
+
+#--------------------------------------------------------
+#   claude-box image
+#--------------------------------------------------------
 
 claude() {
     podman build \
@@ -34,6 +42,10 @@ claude() {
         -t "${OCI_REGISTRY}/${OCI_ORGANIZATION}/${PROJECT_NAME}:latest" \
         "${ROOT_DIR}"
 }
+
+#--------------------------------------------------------
+#   AI Skill artifacts
+#--------------------------------------------------------
 
 list_available_skills() {
     for dir in "${ANTHROPIC_SKILLS_DIR}"/*; do
@@ -229,6 +241,9 @@ EOF
     $COMMAND "$@"
 }
 
+#--------------------------------------------------------
+#   AI Agent artifacts
+#--------------------------------------------------------
 
 list_available_agents() {
     for dir in "${AGENCY_AGENT_DIR}"/*; do
@@ -438,6 +453,190 @@ EOF
     $COMMAND "$@"
 }
 
+#--------------------------------------------------------
+#   MCP Server
+#--------------------------------------------------------
+
+list_available_mcps() {
+    for dir in "${MCP_DIR}"/*; do
+
+        if [[ -d "${dir}" ]]; then
+            name=$(basename "${dir}")
+            echo "${name}"
+        fi
+    done
+}
+
+list_available_oci_mcps() {
+    local mcp_servers=$(podman image ls --format "{{.Repository}}:{{.Tag}}" | grep "${OCI_REGISTRY}/${OCI_ORGANIZATION}/")
+    
+    for image in $mcp_servers; do
+        if [[ "${image}" == "${OCI_REGISTRY}/${OCI_ORGANIZATION}/${MCP_IMAGE_PREFIX}"* ]]; then
+            echo $image
+        fi
+    done
+}
+
+
+remove_mcps() {
+    REMOVE_MCP_USAGE=$(cat <<'EOF'
+Remove OCI images with MCP server.
+
+Usage:
+    claude-box-builder mcps remove [options]
+
+Flags:
+    --name (required)   The name of the MCP server to remove
+    -h, --help          Print help
+EOF
+)
+    NAME=""
+    while [[ $# -gt 0 ]]; do
+        case $1 in
+            --name)
+                shift
+                NAME="${1}"
+                shift
+                ;;
+            -h|--help)
+                echo "$REMOVE_MCP_USAGE"
+                exit 0
+                ;;
+            -*|--*)
+                echo "Unknown option $1"
+                echo "$REMOVE_MCP_USAGE"
+                exit 1
+                ;;
+            *)
+                echo "Unknown positional argument: $1"
+                echo "$REMOVE_MCP_USAGE"
+                exit 1
+                ;;
+        esac
+    done
+
+    if [[ -z "${NAME}" ]]; then
+        echo "--name is required"
+        exit 1
+    fi
+
+    mapfile -t available_oci_mcps < <(list_available_oci_mcps)
+    for mcp in "${available_oci_mcps[@]}"; do
+        if [[ "${mcp}" == $NAME ]]; then
+            podman rmi "${mcp}"
+        fi
+    done
+}
+
+build_mcps() {
+    BUILD_MCP_USAGE=$(cat <<'EOF'
+Build OCI images with MCP server.
+
+Usage:
+    claude-box-builder mcps build [options]
+
+Flags:
+    --name (required)   Build only the MCP server identified by name
+    -h, --help          Print help
+EOF
+)
+    NAME=""
+    while [[ $# -gt 0 ]]; do
+        case $1 in
+            --name)
+                shift
+                NAME="${1}"
+                shift
+                ;;
+            -h|--help)
+                echo "$BUILD_MCP_USAGE"
+                exit 0
+                ;;
+            -*|--*)
+                echo "Unknown option $1"
+                echo "$BUILD_MCP_USAGE"
+                exit 1
+                ;;
+            *)
+                echo "Unknown positional argument: $1"
+                echo "$BUILD_MCP_USAGE"
+                exit 1
+                ;;
+        esac
+    done
+
+    if [[ -z "${NAME}" ]]; then
+        echo "--name is required"
+        exit 1
+    fi
+
+    mapfile -t available_mcps < <(list_available_mcps)
+    for mcp in "${available_mcps[@]}"; do
+        if [[ "${mcp}" == $NAME ]]; then
+            MCP_SERVER_DIR=$(realpath "${MCP_DIR}/${mcp}")
+            podman build \
+                -t "${OCI_REGISTRY}/${OCI_ORGANIZATION}/${MCP_IMAGE_PREFIX}-${mcp}:latest" \
+                -f "${MCP_SERVER_DIR}/Containerfile" \
+                "${MCP_SERVER_DIR}"
+        fi
+    done
+}
+
+mcps(){
+    MCPS_USAGE=$(cat <<'EOF'
+Operations for MCP servers
+
+Usage:
+    claude-box-builder mcps [commands]
+    claude-box-builder mcps [options]
+
+Available commands:
+    ls          List all available mcps
+    oci-ls      List locally available OCI images with MCP servers
+    build       Build OCI image for the selected MCP server
+    remove      Remove OCI image for the selected MCP server
+
+Flags:
+    -h, --help  Print help
+EOF
+)
+
+    COMMAND=""
+    case $1 in
+        ls)
+            COMMAND=list_available_mcps
+            shift
+            ;;
+        oci-ls)
+            COMMAND=list_available_oci_mcps
+            shift
+            ;;
+        build)
+            COMMAND=build_mcps
+            shift
+            ;;
+        remove)
+            COMMAND=remove_mcps
+            shift
+            ;;
+        -h|--help)
+            echo "${MCPS_USAGE}"
+            exit 0
+            ;;
+        *)
+            echo "Unknown positional argument: $1"
+            echo "${MCPS_USAGE}"
+            exit 1
+            ;;
+    esac
+
+    $COMMAND "$@"
+}
+
+#
+#
+#
+
 BASIC_USAGE=$(cat <<'EOF'
 CLI to build OCI artifacts for skills and agents
 
@@ -447,6 +646,7 @@ Usage:
 Available commands:
     skills      Build OCI artifacts for skills
     agents      Build OCI artifacts for agents
+    mcps        Build OCI image for MCP servers
     clean       Remove all temporary files
 
 Flags:
@@ -466,6 +666,10 @@ case $1 in
         ;;
     agents)
         COMMAND=agents
+        shift
+        ;;
+    mcps)
+        COMMAND=mcps
         shift
         ;;
     clean)
